### ISSUE TITLE
ACL statistics (Tiru)

### ISSUE THREAD

**Issue by boucadair** [boucadair/filter-control#1]
It looks useful to return the activated ACL statistics, for example If the client activates a rate-limit ACL, the ACL could be applied at the PE router 
(because the DMS is not capable of handling the attack volume). The rate-limit ACL will rate-limit both legitimate and attack traffic, and the DMS will scrub the rate-limited traffic and drop the attack traffic. The client may want to know the statistics of the traffic dropped because of the rate-limit ACL.

**Comment by mrdeep1** [comment]
The advantage of separating out the counters for the different ACLs is that the DOTS client can then determine what is being effective or not.  However, if (signal) data is able to get from the DOTS server to the DOTS client, then it is likely that the data channel will still be operable and can be used to get these numbers.

I think that that the GET response (or observe response) bytes-dropped etc. should be the total dropped - i.e. the sum of the ACls and what the DMS is otherwise doing as it refers to the mitigation request.

**Comment by boucadair** [comment]
As agreed in the mailing list, this one will be discussed as part of the DOTS telemetry draft.
