### ISSUE TITLE
Use of acl-* should be acl-name in most cases in the text

### ISSUE THREAD

**Issue by mrdeep1** [boucadair/filter-control#2]
acl-name is the only acl-* that a client can send in a request to a server - the others are only used for conflict responses.

E.g. 
A DOTS client may include acl-* attributes in a mitigation request

should be

A DOTS client may include the acl-name attribute in a mitigation request

**Comment by mrdeep1** [comment]
A bit quick off the mark - acl-list is valid, but acl-type is not.

**Comment by boucadair** [comment]
acl-name cannot be included without including acl-list.
acl-type is optional since acl-name is sufficient to identify the ACL. Including it would be valid, but it is completely fine to recommend against including acl-type by replacing acl-* with "acl-list and acl-name". That's would be aligned with the YANG module. 

Will fix this. Thanks
